#!/bin/bash

bspc monitor -d 一 二 三 四 五 六 七 八 九 十
for i in $(bspc query -D --names)
do
    bsp-layout set tall $i -- --master-size 0.65 &
done

bspc config border_width         10
bspc config focused_border_color "#daa6ca"
bspc config normal_border_color "#282e3a"

ln -s $WALLPAPERS/nord-theme $HOME/.config/GIMP/2.10/splashes

$HOME/.config/bspwm/bspborders &
